### ISSUE TITLE
Library won't compile properly

### ISSUE THREAD

**Issue by pcon** [Syndlex/esphome-pxmatrix-component#2]
I've added the following to my configuration and when I try to install it I get an error

```
external_components:
  - source:
      url: https://github.com/Syndlex/esphome-pxmatrix-component.git
      type: git
    components: [ pxmatrix ]

display:
  platform: pxmatrix
  id: my_display
  brightness: 150
  lambda: |-
    it.line(0, 0, 10, 10);
```

Error
```
src/esphome/components/pxmatrix/pxmatrix_display.cpp:1:10: fatal error: pxmatrix.h: No such file or directory
```
